Clasificacion:
- "Fertilizante L\xEDquido"
- Fitoregulador
- Fungicida
- Insecticida
- Acaricida
Empresas:
- Agregar
- Albaugh
- Algas Pacific
- Altiara
- AMVAC
control:
- Agregar
- "Tiz\xF3n Tard\xEDo"
- Mancha de la hoja
- Mancha Gris
- Botrytis
- Damping-off
etiqueta:
- S/color
- Amarillo
- Azul
- Blanco
- Morado
- Verde
favorece:
- Fruto
- Raiz
modoAccion:
- "Bioestimulaci\xF3n"
- Enrraizador
- Promotor de microorganismos
- balance hormonal
- "Sist\xE9mico"
- Contacto
- "Ingesti\xF3n"
- Traslaminar
modoAplicacion:
- Foliar/Drench
- Riego
- "Preparaci\xF3n de mezclas"
productosRegistrados:
- Algas Pacific/Ecoterra_v1.1.pdf
- Algas Pacific/Ecoterra_v1.1.pdf
- Albaugh/Ecoterra_v1.1.pdf
- Albaugh/Ecoterra_v1.1.pdf
- Altiara/ALTIARA- asphix90.pdf
- Albaugh/ALBAUGH-hibioHi10Sc.pdf
- Albaugh/ALBAUGH-hibioHi20Wg.pdf
- Algas Pacific/ALGAS PACIFIC-znKelp.pdf
- Trial2/Ecoterra_v1.1.pdf
- BASF/BASF-cabrio.pdf
